name: 'OS Update'
description: 'Install required Apt Packages'

runs:
  using: "composite"
  steps:
  - name: Add Apt Repo for GCC 11
    shell: bash
    run: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update

  - name: Install Extra Apt Packages
    uses: jroddev/cache-apt-pkgs-action@master
    with:
      # GCC/G++ 11 required for some C++20 features
      # libegl-dev libglu1-mesa-dev mesa-common-dev required for OpenGL
      packages: g++-11 libstdc++-11-dev libegl-dev libglu1-mesa-dev mesa-common-dev
      version: 1.2

  - name: Apply G++11
    shell: bash
    run: |
      sudo apt install -y g++-11 libstdc++-11-dev libegl-dev libglu1-mesa-dev mesa-common-dev
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/gcc-11 110
