name: 'OS Update'
description: 'Install required Apt Packages'

runs:
  using: "composite"
  steps:
  - name: Add Apt Repo for GCC 11
    shell: bash
    run: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update
      #apt-cache policy | awk '/http.*amd64/{print$2}' | sort -u
      #apt-cache search g++ | grep g++
      
      echo "######### explicit"
      echo "searching for g++"
      apt-cache search g++ | grep g++
      
      package="g++-11"
      echo "#########"
      echo "searching for $package"
      apt-cache search $package

  - name: Install Extra Apt Packages
    uses: awalsh128/cache-apt-pkgs-action@v1
    with:
      # G++ 11 required for some C++20 features
      # g\\++-1 slashes required to escape regex: apt-cache search ^g\++-11$
      # libegl-dev libglu1-mesa-dev mesa-common-dev required for OpenGL
      packages: g\++-11 libegl-dev libglu1-mesa-dev mesa-common-dev
      version: 1.0

  - name: Apply G++11
    shell: bash
    run: |
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110
