name: 'OS Update'
description: 'Install required Apt Packages'

runs:
  using: "composite"
  steps:
  - name: Install GCC 11
    shell: bash
    run: |
      echo "Installing G++ 11"
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo apt update && sudo apt install gcc-11 g++-11
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110

  - name: Install OpenGL and GlEW
    shell: bash
    run: |
      echo "=============================="
      echo "=============================="
      echo "Installing Graphics Dependencies"
      sudo apt-get install -y libegl-dev libglu1-mesa-dev mesa-common-dev
