name: 'OS Update'
description: 'Install required Apt Packages'

runs:
  using: "composite"
  steps:
  - name: Add Apt Repo for GCC 11
    shell: bash
    run: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update

  - name: Install Extra Apt Packages
    uses: jroddev/cache-apt-pkgs-action@master
    with:
      # GCC/G++ 11 required for some C++20 features
      # libegl-dev libglu1-mesa-dev mesa-common-dev required for OpenGL
      packages: gcc-11 g++-11 libstdc++-11-dev libegl-dev libglu1-mesa-dev mesa-common-dev
      version: 1.2

  - name: Apply G++11
    shell: bash
    run: |
      echo "BEFORE ##########"
       ls -la /usr/bin/c++
      ls -la /etc/alternatives/c++
      c++ --version
      g++ --version
      gcc --version
      echo "##################"
      
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11
      
      echo "AFTER ##########"
      ls -la /usr/bin/c++
      ls -la /etc/alternatives/c++
      c++ --version
      g++ --version
      gcc --version
      apt list --installed libstdc++\*
