name: 'Conan Install'
description: 'Install and cache conan dependencies'

inputs:
  build_dir:
    description: "cmake build directory"
    required: true
  build_type:
    description: "cmake build type"
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps:
    - name: Cache Conan Dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-conan-deps
      with:
        path: ~/.conan
        key: ${{ runner.os }}-${{ env.cache-name }}-1.0
    - name: Configure CMake (trigger Conan Install)
      run: cmake -B ${{ inputs.build_dir }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}